branch-defaults:
  additional-data:
    environment: Sandwiches---A-Club-dev
    group_suffix: null
  aws-deploy:
    environment: sandwiches
  master:
    environment: sandwiches
environment-defaults:
  sandwiches:
    branch: null
    repository: null
global:
  application_name: Sandwiches---A-Club
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Ruby 2.6 (Passenger Standalone)
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
