branch-defaults:
  aws-deploy:
    environment: sandwiches
environment-defaults:
  sandwiches:
    branch: null
    repository: null
global:
  application_name: sandwiches
  default_ec2_keyname: aws-eb2
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Passenger with Ruby
    2.6 running on 64bit Amazon Linux/2.10.2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
